site_name: Nutanix Solutions
site_url: https://ntx-sol.howntnx.win/
site_description: >-
  The one-stop shop for all Nutanix Solutions. 


# Repository
repo_url: https://github.com/nutanix-japan/ntx-sol.git
repo_name: nutanix-japan/ntx-sol
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2016 - 2026 Nutanix
theme:
  palette:
  #   - primary: deep purple
  #   - accent: black

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.path
  - navigation.footer
  - navigation.tracking
  # - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  # - navigation.expand
  - navigation.top
  - navigation.integrateåß
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.annotate
  - content.code.select
  # - toc.integrate
  #- content.tabs.link

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- attr_list
- md_in_html
- pymdownx.keys
- markdown_grid_tables

plugins:
- search
- social
- git-revision-date-localized:
    enable_creation_date: true
    enabled: !ENV [CI, false]

# Site navigation

nav:
- Home: index.md